### ISSUE TITLE
Shortcut for compile ?

### ISSUE THREAD

**Issue by fabianp** [thehogfather/brackets-latex#20]
Great project by the way!

Used to Sublime, where Ctrl+b would compile the latex source I feel I am very slow finding the TeX button and then hitting compile. Is there a keyboard shortcut or a workaround ?

Thanks

**Comment by thehogfather** [comment]
This should now be fixed although the default shortcut for compilation has been set to `Ctrl-Alt-B` -since `Ctrl-B` is already taken by brackets.

**Comment by fabianp** [comment]
Works perfect. Thanks!
