### ISSUE TITLE
LuaLaTeX compiler support

### ISSUE THREAD

**Issue by starlinq** [thehogfather/brackets-latex#21]
FEATURE request: It would be really nice if the extension could support a lualatex compiler which becomes more popular nowdays!

**Comment by thehogfather** [comment]
Can you share a basic document written to be compiled in lualatex? Then I can work on adding support for it. I dont imagine it would be a difficult feature to implement.

**Comment by starlinq** [comment]
% !TeX program = lualatex

% compile under Windows with command: 
% lualatex.exe -synctex=1 -interaction=nonstopmode -shell-escape %.tex

\documentclass{article}
\usepackage{luacode}

\begin{document}
A random number:
\begin{luacode}
  tex.print(math.random())
\end{luacode}
\end{document}

**Comment by thehogfather** [comment]
If you could install and test the update (from url) that would be great. It contains support for lualatex - although for the moment it does not pass the special arguments `-synctex=1 -interaction=nonstopmode -shell-escape`

**Comment by starlinq** [comment]
lualatex: Compiling C:/lualatex/test.tex

This is LuaTeX, Version beta-0.79.1 (TeX Live 2014/W32TeX) (rev 4971) 
 restricted \write18 enabled.
(./test.tex
LaTeX2e &lt;2014/05/01&gt;
Babel &lt;3.9l&gt; and hyphenation patterns for 79 languages loaded.
(c:/texlive/2014/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(c:/texlive/2014/texmf-dist/tex/latex/base/size10.clo))
(c:/texlive/2014/texmf-dist/tex/lualatex/luacode/luacode.sty
(c:/texlive/2014/texmf-dist/tex/generic/oberdiek/ifluatex.sty)
(c:/texlive/2014/texmf-dist/tex/luatex/luatexbase/luatexbase.sty
(c:/texlive/2014/texmf-dist/tex/generic/oberdiek/luatex.sty
(c:/texlive/2014/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(c:/texlive/2014/texmf-dist/tex/latex/etex-pkg/etex.sty)
(c:/texlive/2014/texmf-dist/tex/generic/oberdiek/luatex-loader.sty
(c:/texlive/2014/texmf-dist/scripts/oberdiek/oberdiek.luatex.lua)))
(c:/texlive/2014/texmf-dist/tex/luatex/luatexbase/luatexbase-compat.sty)
(c:/texlive/2014/texmf-dist/tex/luatex/luatexbase/luatexbase-modutils.sty
(c:/texlive/2014/texmf-dist/tex/luatex/luatexbase/luatexbase-loader.sty
(c:/texlive/2014/texmf-dist/tex/luatex/luatexbase/luatexbase.loader.lua))
(c:/texlive/2014/texmf-dist/tex/luatex/luatexbase/modutils.lua))
(c:/texlive/2014/texmf-dist/tex/luatex/luatexbase/luatexbase-regs.sty)
(c:/texlive/2014/texmf-dist/tex/luatex/luatexbase/luatexbase-attr.sty
(c:/texlive/2014/texmf-dist/tex/luatex/luatexbase/attr.lua))
(c:/texlive/2014/texmf-dist/tex/luatex/luatexbase/luatexbase-cctb.sty
(c:/texlive/2014/texmf-dist/tex/luatex/luatexbase/cctb.lua))
(c:/texlive/2014/texmf-dist/tex/luatex/luatexbase/luatexbase-mcb.sty
(c:/texlive/2014/texmf-dist/tex/luatex/luatexbase/mcb.lua))))
(c:/lualatex/out/test.aux) [1{c:/texlive/2014/texmf-var/fonts/map/pdftex/updmap/
pdftex.map}] (c:/lualatex/out/test.aux))
 263 words of node memory still in use:
   2 hlist, 1 vlist, 1 rule, 2 glue, 40 glue_spec, 1 write nodes
   avail lists: 2:13,3:2,4:28,5:3,6:43,7:1,9:6,10:2

Output written on test.pdf (1 page, 14055 bytes).
Transcript written on test.log.

**Comment by thehogfather** [comment]
marking as closed as the main issue has been resolved. The issue with the pdf viewer is probably best opened as separate - though I am not sure how to sort that out.
