### ISSUE TITLE
preferences should be defined at the project level 

### ISSUE THREAD

**Issue by thehogfather** [thehogfather/brackets-latex#23]
Preferences for properties like the preferred compiler or the output folder for compiled files should be defined per project with reasonable default settings.

**Comment by machocam** [comment]
@thehogfather thank you very much for the development of this plugin. Great help for my work. 

I thin that this idea of the setting being different per project is interesting. How do I make it so the output files are all in the same location as the original .tex file that I'm compiling is in ?

**Comment by thehogfather** [comment]
@machocam you can set this up using the settings dialog. `File > Latex Settings ..`. You can then put a path in the field that says `output directory for compiled files and logs`.

Not that if you are using a relative path, that path is relative to the project folder. Hence if the file you are compiling is in the root of the current project then just put a `.` in the text field.

Hope this helps. If there is a feature that would make life easier, please file an issue.

**Comment by machocam** [comment]
Sounds good. Will do. Thanks a lot!

**Comment by machocam** [comment]
For some reason the plugin won't save my settings actually. I entered a "."
and it just reverts back to "out".

**Comment by thehogfather** [comment]
could you let me know what operating system you are running?

**Comment by machocam** [comment]
OSX

On Fri, Jul 3, 2015 at 11:24 AM, Patrick Oladimeji <notifications@github.com

**Comment by thehogfather** [comment]
and can you confirm you are running the latex version of the extension - from github not the registry?

**Comment by machocam** [comment]
Oh that I cannot confirm. I installed from the registry. How do you install
from github?

Will do that tonight and let you know if it works.

On Fri, Jul 3, 2015 at 11:29 AM, Patrick Oladimeji <notifications@github.com

**Comment by thehogfather** [comment]
Do `File > Extension Manager` then `Install from url` and put this url `https://github.com/thehogfather/brackets-latex` in the text box. Also can I check if you have more than one instance of brackets open when you change the setting?

**Comment by machocam** [comment]
Ok I'll do that and get back to you in 6 hours or so.



On Fri, Jul 3, 2015 at 11:33 AM, Patrick Oladimeji <notifications@github.com

**Comment by machocam** [comment]
I installed straight from source. Restarted, only one instance; and still
the setting seems to revert to "out". Let me know if I can do anything else
to help you out.

**Comment by thehogfather** [comment]
@machocam I have reopened a separate issue #25  to address the preference persistence problem.
