### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by inktvis75** [thehogfather/brackets-latex#26]
Hi,
Is it possible to add arara support (as compile option),
I use arara for texlive + lilypond, see e.g. http://tex.stackexchange.com/questions/111055/how-to-run-latex-and-lilypond-book-in-one-command

**Comment by thehogfather** [comment]
@inktvis75 would this workflow typically result in the creation of a pdf?

**Comment by inktvis75** [comment]
yes it will create a pdf

**Comment by inktvis75** [comment]
thank you very much for this solution !
