### ISSUE TITLE
Cannot compile .tex documents

### ISSUE THREAD

**Issue by edelsonc** [thehogfather/brackets-latex#28]
Hello

I am unable to compile .tex documents. There error in the developer tool is show in the attached screenshot

Thanks
![screen shot 2016-07-07 at 1 40 44 am](https://cloud.githubusercontent.com/assets/18823568/16643594/0db81376-43e4-11e6-86f7-8ab2ced5503c.png)

**Comment by boylec** [comment]
Same

**Comment by thehogfather** [comment]
could you both confirm what version of brackets you are running?

**Comment by thehogfather** [comment]
@edelsonc @boylec kindly update the extension if you are still using it-  the issue would have been resolved in todays update.
