### ISSUE TITLE
setup guide?

### ISSUE THREAD

**Issue by Marchuck** [thehogfather/brackets-latex#30]
Hello maybe this question is dumb, but I am new into Brackets. How can I setup latex with brackets?

Thanks in advance.

ps. I am using OSX.

**Comment by thehogfather** [comment]
@Marchuck you will need to install Tex e.g., from http://latex-project.org/
Once that is done (and the extension is installed), you will need to check that the path to the tex bin folder is correctly set by going to `File`>`Latex Settings`

For me the path is `/Library/TeX/texbin` (although this might be slightly different for different versions of TeX)
